# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-c9xxWKubcSQmxzQbOwuIMkMozbT2cc
"""

Principal()

def Principal():
  print("Digite o primeiro número")
  num1 = float(input())
  print("Digite o segundo número")
  num2 = float(input())
  print("Digite o operador \n 1 - Somar \n 2 - Subtrair \n 3 - Multiplicar \n 4 - Dividir ")
  operador = float(input())

  resultado = ( Calcular(num1, num2, operador))

  print(resultado)
  if resultado == "Operador inválido":
    Principal()

  print("Deseja realizar outro calculo \n y-sim ou n-não")
  continuar = input()

  match continuar:
    case 'y':
      Principal()
    case 'n':
      print("Fim do programa")
    case _:
        print("Comando Invalido")

def Calcular(num1, num2, operador):
  match operador:
    case 1:
      return num1 + num2

    case 2:
      return num1 - num2

    case 3:
      return num1 * num2

    case 4:
      return num1 / num2

    case _:
      return "Operador inválido"